name: smart_parking
description: A professional smart parking mobile app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  qr_code_scanner: any
  http: any
  provider: any
  shared_preferences: any
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.2.2
  qr_flutter: ^4.1.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true